apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa
  labels:
    app: opa
    SupportGroup: WP-DTS-Hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
        SupportGroup: WP-DTS-Hydra
      name: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:edge
        ports:
        - name: opa-http
          containerPort: 8181
        args:
        - "run"
        - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
        - "--server"
        - "/policies"
        volumeMounts:
        - readOnly: true
          mountPath: /policies
          name: opa-policies
      volumes:
      - name: opa-policies
        configMap:
          name: opa-policies