apiVersion: v1
kind: Service
metadata:
  labels:
    app: opa
  name: opa
  namespace: opa
spec:
  ports:
  - name: 8181-8181
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: opa
    SupportGroup: WP-DTS-Hydra
  type: ClusterIP
status:
  loadBalancer: {}
